import { useEffect, useState } from 'react';
import { ArrowLeft, BadgeCheck, Briefcase, MapPin, ShieldCheck } from 'lucide-react';
import { TopNav } from '../components/TopNav';
import { Avatar, MicButton, StarRating } from '../components/ui';
import type { ApiContractorProfile, ScreenId } from '../types';
import { apiGetContractorPublicProfile } from '../lib/api';
export function ContractorPublicProfile({ onNavigate, contractorId }: { onNavigate: (id: ScreenId) => void; contractorId: string | null }) {
  const [contractor, setContractor] = useState<ApiContractorProfile | null>(null); const [error, setError] = useState('');
  useEffect(() => { if (!contractorId) { setError('No contractor was selected.'); return; } setContractor(null); setError(''); apiGetContractorPublicProfile(contractorId).then((r) => setContractor(r.contractor)).catch(() => setError('This contractor profile is not available right now.')); }, [contractorId]);
  return <div className="min-h-screen bg-white"><TopNav onNavigate={onNavigate} /><main className="mx-auto max-w-3xl px-4 py-6"><button onClick={() => onNavigate('client-home')} className="mb-5 flex items-center gap-1 text-sm text-gray-500"><ArrowLeft className="h-4 w-4" /> Back to dashboard</button>{error ? <p className="rounded-xl bg-red-50 p-4 text-red-700">{error}</p> : !contractor ? <p className="py-20 text-center text-gray-500">Loading contractor profile…</p> : <><section className="rounded-2xl border border-gray-100 bg-gray-50 p-5 shadow-soft"><div className="flex gap-4"><Avatar src={contractor.profileImage} alt={contractor.fullName} size="lg" /><div><div className="flex items-center gap-2"><h1 className="text-2xl font-bold text-navy-700">{contractor.fullName}</h1>{(contractor.isVerified || contractor.kycStatus === 'VERIFIED') && <BadgeCheck className="h-5 w-5 text-emerald-500" />}</div><p className="mt-1 text-gray-500">{contractor.primaryTrade || contractor.specializations?.[0] || 'Contractor'}</p><div className="mt-3 flex flex-wrap gap-4 text-sm text-gray-600"><span className="flex items-center gap-1"><StarRating rating={contractor.averageRating || 0} /> {contractor.averageRating || 0} ({contractor.totalReviews || 0})</span>{contractor.city && <span className="flex items-center gap-1"><MapPin className="h-4 w-4 text-amber-500" /> {contractor.city}</span>}</div></div></div></section><section className="mt-5 rounded-xl border border-gray-100 p-5"><h2 className="font-semibold text-navy-700">About</h2><p className="mt-2 text-sm leading-6 text-gray-600">{contractor.about || 'No biography has been added yet.'}</p></section><div className="mt-5 grid gap-4 sm:grid-cols-2"><section className="rounded-xl border border-gray-100 p-5"><Briefcase className="h-5 w-5 text-amber-500" /><h2 className="mt-2 font-semibold text-navy-700">Experience</h2><p className="mt-1 text-sm text-gray-600">{contractor.experienceYears || 0} years · {contractor.completedProjects || 0} projects completed</p></section><section className="rounded-xl border border-gray-100 p-5"><ShieldCheck className="h-5 w-5 text-emerald-500" /><h2 className="mt-2 font-semibold text-navy-700">Verification</h2><p className="mt-1 text-sm text-gray-600">{contractor.kycStatus === 'VERIFIED' ? 'Identity verified' : 'Verification pending'}</p></section></div>{(contractor.portfolioImages?.length || 0) > 0 && <section className="mt-6"><h2 className="font-semibold text-navy-700">Portfolio</h2><div className="mt-3 grid grid-cols-2 gap-3 sm:grid-cols-3">{(contractor.portfolioImages || []).map((image, i) => <img key={`${image}-${i}`} src={image} alt={`${contractor.fullName} portfolio`} className="aspect-square rounded-xl object-cover" />)}</div></section>}</>}</main><MicButton /></div>;
}
