import mongoose, { Document, Schema } from 'mongoose';

export type MessageStatus = 'sent' | 'delivered' | 'read';

export interface IMessage extends Document {
  conversationId: mongoose.Types.ObjectId;
  senderId: mongoose.Types.ObjectId;       // Always set by server from JWT — never trusted from client
  clientMessageId: string;                 // UUID generated by client — used for idempotency
  body: string;
  status: MessageStatus;
  editedAt: Date | null;
  deletedAt: Date | null;                  // Soft delete — message still exists in DB
  createdAt: Date;
  updatedAt: Date;
}

const MessageSchema = new Schema<IMessage>(
  {
    conversationId: {
      type: Schema.Types.ObjectId,
      ref: 'Conversation',
      required: true,
      index: true,
    },
    senderId: {
      type: Schema.Types.ObjectId,
      ref: 'User',
      required: true,
    },
    // UUID v4 sent by the client browser so the server can detect retries
    clientMessageId: {
      type: String,
      required: true,
      trim: true,
    },
    body: {
      type: String,
      required: [true, 'Message body is required'],
      trim: true,
      maxlength: [4000, 'Message cannot exceed 4000 characters'],
    },
    status: {
      type: String,
      enum: ['sent', 'delivered', 'read'],
      default: 'sent',
    },
    editedAt: { type: Date, default: null },
    deletedAt: { type: Date, default: null },
  },
  { timestamps: true }
);

// Primary query: paginated message history for a conversation
MessageSchema.index({ conversationId: 1, createdAt: 1 });

// Idempotency: prevent duplicate messages from retried sends
MessageSchema.index(
  { conversationId: 1, senderId: 1, clientMessageId: 1 },
  { unique: true }
);

export const Message = mongoose.model<IMessage>('Message', MessageSchema);
