import { useMemo, useState } from 'react';
import { ChevronRight, Search, X } from 'lucide-react';
import { Avatar } from './ui';
import type { ApiContractor } from '../lib/api';
export function ContractorSearch({ contractors, loading, onSelect }: { contractors: ApiContractor[]; loading: boolean; onSelect: (id: string) => void }) {
  const [query, setQuery] = useState('');
  const matches = useMemo(() => { const q = query.trim().toLowerCase(); return q ? contractors.filter((c) => [c.fullName, c.specialization, c.city].filter(Boolean).some((value) => value!.toLowerCase().includes(q))) : []; }, [contractors, query]);
  return <section className="mt-6"><label htmlFor="contractor-search" className="mb-2 block text-sm font-semibold text-navy-700">Find a contractor</label><div className="relative"><Search className="pointer-events-none absolute left-3 top-1/2 h-5 w-5 -translate-y-1/2 text-gray-400" /><input id="contractor-search" value={query} onChange={(e) => setQuery(e.target.value)} placeholder="Search by contractor name, trade, or city" className="w-full rounded-xl border border-gray-200 py-3 pl-10 pr-10 text-sm outline-none focus:border-navy-400 focus:ring-2 focus:ring-navy-100" />{query && <button type="button" aria-label="Clear search" onClick={() => setQuery('')} className="absolute right-3 top-1/2 -translate-y-1/2 text-gray-400"><X className="h-5 w-5" /></button>}</div>{query.trim() && <div className="mt-2 overflow-hidden rounded-xl border border-gray-200 bg-white shadow-soft">{loading ? <p className="p-4 text-sm text-gray-500">Searching contractors…</p> : matches.length === 0 ? <p className="p-4 text-sm text-gray-500">No contractors match “{query.trim()}”.</p> : matches.slice(0, 6).map((c) => <button type="button" key={c._id} onClick={() => onSelect(c._id)} className="flex w-full items-center gap-3 border-b border-gray-100 p-3 text-left last:border-b-0 hover:bg-navy-50"><Avatar src={c.profileImage} alt={c.fullName} size="md" /><span className="min-w-0 flex-1"><span className="block truncate font-semibold text-navy-700">{c.fullName}</span><span className="block truncate text-xs text-gray-500">{c.specialization || 'General Works'}{c.city ? ` · ${c.city}` : ''}</span></span><ChevronRight className="h-5 w-5 text-gray-400" /></button>)}</div>}</section>;
}
